channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python=3
  - numpy
  - biopython
  - django
  - matplotlib
  - pandas==1.5.3
  - plumbum
  - scipy==1.5.3
  - scikit-bio==0.5.6
  - openpyxl
  - xlrd
  - blast
  - iqtree
  - mafft
  - mothur==1.43.0
  - psycopg2
  - werkzeug
  - textdistance
  - beautifulsoup4