name: symportal
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  # tools
  - python=3
  - blast==2.14.0
  - iqtree==2.2.2.3
  - mafft==7.520
  - mothur==1.43.0
  # packages
  - asgiref==3.6.0
  - asttokens==2.2.1
  - backcall==0.2.0
  - backports.functools-lru-cache==1.6.4
  - backports.zoneinfo==0.2.1
  - bcrypt==3.2.2
  - beautifulsoup4==4.12.2
  - biopython==1.81
  - brotlipy==0.7.0
  - CacheControl==0.12.11
  - certifi==2022.12.7
  - cffi==1.15.1
  - charset-normalizer==3.1.0
  - colorama==0.4.6
  - contourpy==1.0.7
  - cryptography==39.0.0
  - cycler==0.11.0
  - Cython==0.29.34
  - decorator==5.1.1
  - Django==4.2.1
  - et-xmlfile==1.1.0
  - exceptiongroup==1.1.1
  - executing==1.2.0
  - fonttools==4.39.3
  - hdmedians==0.14.2
  - idna==3.4
  - importlib-metadata==6.6.0
  - iniconfig==2.0.0
  - ipython==8.12.1
  - jedi==0.18.2
  - joblib==1.2.0
  - kiwisolver==1.4.4
  - lockfile==0.12.2
  - MarkupSafe==2.1.2
  - matplotlib==3.6.3
  - matplotlib-inline==0.1.6
  - msgpack==1.0.5
  - munkres==1.1.4
  - natsort==8.3.1
  - numpy==1.24.3
  - olefile==0.46
  - openpyxl==3.1.2
  - packaging==23.1
  - pandas==2.0.1
  - paramiko==3.1.0
  - parso==0.8.3
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - Pillow==8.4.0
  - pip==23.1.2
  - pluggy==1.0.0
  - plumbum==1.8.1
  - ply==3.11
  - prompt-toolkit==3.0.38
  - psycopg2==2.9.3
  - ptyprocess==0.7.0
  - pure-eval==0.2.2
  - pycparser==2.21
  - Pygments==2.15.1
  - PyNaCl==1.5.0
  - pyOpenSSL==23.1.1
  - pyparsing==3.0.9
  - PySocks==1.7.1
  - pytest==7.3.1
  - python-dateutil==2.8.2
  - pytz==2023.3
  - requests==2.29.0
  - scikit-bio==0.5.6
  - scikit-learn==1.2.2
  - scipy==1.5.3
  - setuptools==67.7.2
  - sip==6.7.9
  - six==1.16.0
  - soupsieve==2.3.2.post1
  - sqlparse==0.4.4
  - stack-data==0.6.2
  - textdistance==4.5.0
  - threadpoolctl==3.1.0
  - tomli==2.0.1
  - tornado==6.3
  - traitlets==5.9.0
  - typing_extensions==4.5.0
  - tzdata==2023.3
  - unicodedata2==15.0.0
  - urllib3==1.26.15
  - wcwidth==0.2.6
  - Werkzeug==2.3.3
  - wheel==0.40.0
  - xlrd==2.0.1
  - zipp==3.15.0
