name: Symportal CI Workfow

on:
  push:
    paths:
      - environment.yml
      - '**/main.yml'
      - '**/setup-conda-env.yml'
      - '**/run-tests.yml'

runs-on: ubuntu-latest

env:
  ENV_NAME: symportal
  CACHE_PATH: /usr/share/miniconda/envs/symportal

jobs:
  setup-conda-env:
    name: Setup Conda env
    steps:
      - name: Create and Cache Conda Environment
        include: setup-conda-env.yml
    if: >
      contains(github.event.head_commit.modified, 'environment.yml')
      || contains(github.event.head_commit.modified, '**/setup-conda-env.yml')

  run-tests:
    name: Run Tests
    defaults:
      run:
        # to not activate conda environment in each task
        shell: bash -l {0}
    steps:
      - name: Run Tests
        include: run-tests.yml
