name: SymPortal Testing

on:
  push:
    branches:
      - set-up-github-actions

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: symportal
        environment-file: environment.yml

    - name: Set up settings.py
      run: |
        mv settings_blank.py settings.py
        sed -i "s/^SECRET_KEY = ''$/SECRET_KEY = '$(base64 /dev/urandom | head -c50)'/" settings.py

    - name: Configure sp_config.py
      run: |
        mv sp_config_blank.py sp_config.py

    - name: Create SQLite database
      run: |
        python manage.py migrate

    - name: Populate local database
      run: |
        python populate_db_ref_seqs.py

    - name: Run tests
      run: |
        python -m tests.tests
