name: SymPortal Testing

on:
  push:
    branches:
      - set-up-github-actions
    paths:
      - environment.yml
      - .github/workflows/run-tests.yml

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        # to not activate conda environment in each task
        shell: bash -l {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml

    - name: Cache Conda environment
      uses: actions/cache@v2
      with:
        path: ${{ env.CONDA_PREFIX }}
        key: conda-${{ hashFiles('environment.yml') }}
        restore-keys: conda-

#    - name: Restore Conda environment from cache
#      uses: actions/cache@v2
#      with:
#        path: ${{ env.CONDA_PREFIX }}
#        key: conda-${{ hashFiles('environment.yml') }}
#        restore-keys: conda-
#
#    # DELETE ME
#    - name: Debug 1
#      run: |
#        mafft -h
#        conda env list
#
#    - name: Set up settings.py
#      run: |
#        mv settings_blank.py settings.py
#        sed -i "s|^SECRET_KEY = ''$|SECRET_KEY = '$(base64 /dev/urandom | head -c50)'|" settings.py
#
#    - name: Configure sp_config.py
#      run: |
#        mv sp_config_blank.py sp_config.py
#
#    - name: Create SQLite database
#      run: |
#        python manage.py migrate
#
#    - name: Populate local database
#      run: |
#        python populate_db_ref_seqs.py
#
#    - name: Run tests
#      run: |
#        python -m tests.tests
